---

- name: Convert to markdown
  template:
    src: convert_markdown.j2
    dest: "{{ path_to }}{{ rulesname |replace(' ','') }}.md"
  vars:
    rules: "{{ inputitem.rules }}"
    rulesname: "{{ inputitem.name }}"
  loop: "{{ dict_list }}"
  loop_control:
    loop_var: inputitem
  register: convertmd_results
  no_log: true

- name: Show results
  debug:
    var: convertmd_results
